### PR TITLE
Properly lift imports as well as classes so extending classes will work

### LINKED ISSUE #386: Compilation error when defining class extending class imported in the same cell
If you import a class and then attempt to define an extending class in the same cell you will get a compiler error, since we don't lift the import when we lift the class up to the package namespace. 

For example a cell with contents: 

```
import org.apache.spark.sql.expressions.UserDefinedAggregateFunction
class MyUDAF extends UserDefinedAggregateFunction { ... }
```

will fail with `not found: type UserDefinedAggregateFunction` because the cell will be rewritten to (essentially): 

```
package $notebook {
  class MyUDAF extends org.apache.spark.sql.expressions.UserDefinedAggregateFunction { ... }
  class Eval$CellX$YYY {
     import org.apache.spark.sql.expressions.UserDefinedAggregateFunction
  }
} 

```

Workaround for now is to put the import into its own cell.

### PR DESCRIPTION
**Pull request by jonathanindig**
Resolves #386 and #388

### CODE REVIEW

File: polynote-kernel/src/main/scala/polynote/kernel/lang/scal/ScalaSource.scala [hunk 1]
```diff
@@ -199,9 +215,11 @@ class ScalaSource[G <: Global](
             atPos(beginning)(global.PrimarySuperCall(ListOfNil)), atPos(beginning)(global.gen.mkSyntheticUnit()))))
 
       // import everything imported by previous cells...
-      val (directImports: List[global.Tree], localImports: List[global.Tree]) = previousSources.flatMap(_.directImports.asInstanceOf[List[global.Tree]]).partition {
+      val (directImports: List[global.Tree], localImports: List[global.Tree]) = previousSources.flatMap(_.directImports.asInstanceOf[List[global.Tree]])
+        .filterNot(imp => trees.exists(_.toString == imp.toString)) // remove any duplicate imports
```
Comment (jonathanindig) [inline polynote-kernel/src/main/scala/polynote/kernel/lang/scal/ScalaSource.scala]: I think this is what solved #388

File: polynote-spark/src/test/scala/polynote/kernel/lang/ScalaSparkInterpreterSpec.scala [hunk 2]
```diff
@@ -175,5 +175,49 @@ class ScalaSparkInterpreterSpec extends FlatSpec with Matchers with SparkKernelS
...
+      """.stripMargin,
+      "new MyImpl().foo"
+    )
+    assertSparkScalaOutput(code) { case (vars, output, displayed) =>
+      vars("Out") shouldEqual 2
+    }
+  }
+
+  // FAILS!!!!
+  it should "work with inner traits if properly imported" ignore {
```
Comment (jonathanindig) [inline polynote-spark/src/test/scala/polynote/kernel/lang/ScalaSparkInterpreterSpec.scala]: @jeremyrsmith Here's the thing that doesn't work that I was showing you earlier.
