### PR TITLE
fix bugs related to comments

### LINKED ISSUE #1412: Problems with editing/deleting root comment
After making a root-level comment (i.e. not replying to an existing comment), the comment cannot be deleted:

```state_handler.ts:192 TypeError: Cannot read properties of undefined (reading 'uuid')``` 

Editing behavior is also inconsistent, but less reproducible than the deletion bug.

### PR DESCRIPTION
**Pull request by mjren23**
- contains fix for preobservers not stopping the propagation to child observers in case of a deleted key 
- fixes multiple comments being allowed on the same selection of text 

fixes #1412

### CODE REVIEW

**Review by jeremyrsmith — APPROVED** [review]
Looks good!

File: polynote-frontend/polynote/ui/component/notebook/cell.ts [hunk 1]
```diff
@@ -806,11 +806,9 @@ abstract class MonacoCell extends Cell {
...
             if (model) {
                 const range = new PosRange(model.getOffsetAt(evt.selection.getStartPosition()), model.getOffsetAt(evt.selection.getEndPosition()));
-                if (evt.selection.getDirection() === SelectionDirection.RTL) {
-                    this.cellState.updateField("currentSelection", () => range.reversed)
-                } else {
-                    this.cellState.updateField("currentSelection", () => range)
-                }
+                // Monaco guarantees that the position from Selection.getStartPosition() will be before or
+                // equal to Selection.getEndPosition(), so we don't need to worry about selection direction
+                this.cellState.updateField("currentSelection", () => range)
```
Comment (jonathanindig) [inline polynote-frontend/polynote/ui/component/notebook/cell.ts:811]: Ah good find! So we were reversing the selection ourselves. I assume Monaco's behavior must have changed at some point in the past few years... 🤔

File: polynote-frontend/polynote/ui/component/notebook/comment.ts [hunk 2]
```diff
@@ -87,7 +87,7 @@ export class CommentHandler extends Disposable {
                    if (maybeRoot && maybeRoot.uuid === commentId) {
                        // If this is a root comment, we delete it and it's children
                        // First, the children
-                       Object.keys(maybeRoot.rootChildren(currentComments)).forEach(commentId => allCommentsState.update(() => removeKey(commentId)))
+                       maybeRoot.rootChildren(currentComments).forEach(childComment => allCommentsState.update(() => removeKey(childComment.uuid)))
```
Comment (jonathanindig) [inline polynote-frontend/polynote/ui/component/notebook/comment.ts:90]: What was the reason for this change? (it's a fine change, just wondering whether it does anything I'm not seeing)

File: polynote-frontend/polynote/ui/component/notebook/comment.ts [hunk 3]
```diff
@@ -279,6 +281,10 @@ class CommentRoot extends MonacoRightGutterOverlay {
         handledChangedComments(this.allCommentsState.state)
         allCommentsState.addObserver((curr, updateResult) => handledChangedComments(curr, updateResult))
 
+        this.rootState.addObserver((curr: CellComment, updateResult: UpdateResult<CellComment>) => {
```
Comment (jonathanindig) [inline polynote-frontend/polynote/ui/component/notebook/comment.ts:284]: I'd bump this up right next to where you set `this.range` initially, just for clarity.

**Review by jonathanindig — APPROVED** [review]
LGTM other than minor comments!

File: polynote-frontend/polynote/ui/component/notebook/comment.ts (hunk 2 above)
Comment (mjren23) [reply polynote-frontend/polynote/ui/component/notebook/comment.ts:90]: the implementation of CommentRoot.rootChildren() returns an array of CellComments indexed with integers (so the first comment has key 0, the next has key 1 etc). so previously, this line (90) was trying to remove comments with ID 0, 1, etc, which don't exist, so if you deleted a root comment that had a reply, both comment and reply would 'disappear' but the child comment wouldn't get deleted and would pop back up if another comment was made on the same selection.

File: polynote-frontend/polynote/ui/component/notebook/cell.ts (hunk 1 above)
Comment (omidmogasemi) [reply polynote-frontend/polynote/ui/component/notebook/cell.ts:811]: Probably from when I updated Monaco a few months ago...oops 🤦‍♂️

File: polynote-frontend/polynote/ui/component/notebook/comment.ts [hunk 4]
```diff
@@ -279,6 +288,7 @@ class CommentRoot extends MonacoRightGutterOverlay {
         handledChangedComments(this.allCommentsState.state)
         allCommentsState.addObserver((curr, updateResult) => handledChangedComments(curr, updateResult))
 
+
```
Comment (omidmogasemi) [inline polynote-frontend/polynote/ui/component/notebook/comment.ts:291]: [nit] Added extra whitespace

File: polynote-frontend/polynote/state/state_handler.test.ts [hunk 5]
```diff
@@ -235,6 +241,56 @@ describe("ObjectStateHandler", () => {
         })
     })
 
+    describe("preobserver", () => {
```
Comment (omidmogasemi) [inline polynote-frontend/polynote/state/state_handler.test.ts:244]: 💯

**Review by omidmogasemi — APPROVED** [review]
Awesome fixes!

File: polynote-frontend/polynote/ui/component/notebook/cell.ts (hunk 1 above)
Comment (jeremyrsmith) [reply polynote-frontend/polynote/ui/component/notebook/cell.ts:811]: We are going to have to keep an eye on Monaco... whenever we update it, we should expect a lot of breakage.

File: polynote-frontend/polynote/state/state_handler.ts [hunk 6]
```diff
@@ -101,10 +103,11 @@ function filterPreObserver<S>(fn: PreObserver<S>, filter?: (src: any) => boolean
     }
 }
 
+// returns an Observer that recursively calls child Observers upon receiving an update
```
Comment (jonathanindig) [inline polynote-frontend/polynote/state/state_handler.ts:106]: where's the recursion here?

File: polynote-frontend/polynote/state/state_handler.ts [hunk 7]
```diff
@@ -321,10 +328,12 @@ export class ObjectStateHandler<S extends object> extends Disposable implements
         this.update(keyUpdater(key, updateFn), updateSource, `${key.toString()}.` + (updateSubPath ?? ''))
     }
 
+    // returns a Disposable that will remove itself from the ObserverDict when disposed
```
Comment (jonathanindig) [inline polynote-frontend/polynote/state/state_handler.ts:331]: I would also add what this function does. e.g. "Adds an observer at a given path that is disposed when this handler is disposed. Returns a Disposable so callers can add introduce additional disposal criteria" (same as addPreObserverAt)

File: polynote-frontend/polynote/ui/component/notebook/comment.ts (hunk 2 above)
Comment (jonathanindig) [reply polynote-frontend/polynote/ui/component/notebook/comment.ts:90]: aha! yikes 🤦
