### PR TITLE
Fix resolvers not copying to clipboard correctly 

### LINKED ISSUE #1403: "Copy Configuration" button does not copy resolvers

### PR DESCRIPTION
**Pull request by mjren23**
- previously, calling JSON.stringify on the configuration object caused the resolver to not be able to be parsed as a specific type of RepositoryConfig. this breaks copy-pasting 
- this changeset adds a toJSON method on each child class of RepositoryConfig to wrap the object along with a "type" property (one of "ivy", "maven", or "pip") and uses that when parsing the JSON back to a NotebookConfig object 

fixes #1403

### CODE REVIEW

File: polynote-frontend/polynote/data/data.ts [hunk 1]
```diff
@@ -84,6 +84,19 @@ export class IvyRepository extends RepositoryConfig {
         return 0;
     }
 
+    // enable parsing when copy-pasting configurations
+    toJSON(): any {
+        return {
+            type: "ivy",
+            resolver: {
```
Comment (jonathanindig) [inline polynote-frontend/polynote/data/data.ts:91]: Could this be simplified using `resolver: ...this`? 

If that works, it's really tempting to lift this all up into `RepositoryConfig` 😅

File: polynote-frontend/polynote/data/data.ts [hunk 2]
```diff
@@ -84,6 +84,19 @@ export class IvyRepository extends RepositoryConfig {
         return 0;
     }
 
+    // enable parsing when copy-pasting configurations
+    toJSON(): any {
```
Comment (jonathanindig) [inline polynote-frontend/polynote/data/data.ts:88]: Can we narrow the `any` typed here? Something like `{type: "ivy" | "maven" | "pip", resolver: RepositoryConfig}` (just writing from memory, not 100% sure about the syntax)

File: polynote-frontend/polynote/ui/component/notebook/notebookconfig.ts [hunk 3]
```diff
@@ -351,6 +351,24 @@ class Resolvers extends Disposable {
             } else { return [] }
         });
     }
+
+    static parseWrappedResolvers(wrappedResolvers: any): RepositoryConfig[] {
+        return wrappedResolvers.map((wrappedResolver: any) => {
```
Comment (jonathanindig) [inline polynote-frontend/polynote/ui/component/notebook/notebookconfig.ts:356]: Same as above - can we narrow the `any` to something more specific?

Comment (mjren23) [reply polynote-frontend/polynote/ui/component/notebook/notebookconfig.ts:356]: not sure - technically the JSON.parse call in the pasteConfig method _thinks_ it's parsing paste.repositories to a RepositoryConfig object (which it isn't, it's the wrapped anon object). the objects inside the array can be that same {type: "ivy" | ...etc } object, but not sure how to get the argument to be more specific without casting paste.repositories to `unknown` first (maybe that's okay?).

File: polynote-frontend/polynote/data/data.ts [hunk 4]
```diff
@@ -71,7 +71,15 @@ export abstract class RepositoryConfig extends CodecContainer {
     static codecs: typeof RepositoryConfig[];
     static msgTypeId: number;
 
-    abstract url: string
+    abstract url: string;
+    abstract repositoryTypeName: "ivy" | "maven" | "pip";
```
Comment (jonathanindig) [inline polynote-frontend/polynote/data/data.ts:75]: [nit] if you define a [type alias](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-aliases) you only need to type `"ivy" | "maven" | "pip"` once (and it makes it a little easier to add a resolver later, not like that its terribly likely to happen tho)

File: polynote-frontend/polynote/ui/component/notebook/notebookconfig.ts [hunk 5]
```diff
@@ -118,7 +118,7 @@ export class NotebookConfigEl extends Disposable {
 
             try {
                 paste = JSON.parse(clipText);
-                let resolvers = Resolvers.parseWrappedResolvers(paste.repositories);
+                let resolvers = Resolvers.parseWrappedResolvers((paste.repositories as unknown) as [{type: "ivy" | "maven" | "pip", resolver: RepositoryConfig}]);
```
Comment (jonathanindig) [inline polynote-frontend/polynote/ui/component/notebook/notebookconfig.ts:121]: Hm. I _ think_ you can do this a little more cleanly (though still kind of ugly) by modifying the type of paste. Rather than `NotebookConfig`, try something like: `Omit<NotebookConfig, "repositories"> & {repositories: [{type: "ivy" | "maven" | "pip", resolver: RepositoryConfig}]}`

https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys

Comment (jonathanindig) [reply polynote-frontend/polynote/ui/component/notebook/notebookconfig.ts:121]: And a type alias for `{type: "ivy" | "maven" | "pip", resolver: RepositoryConfig}` might be a good idea

**Review by jonathanindig — APPROVED** [review]
LGTM, just a couple little type-y nits
