### PR TITLE
Fix several bugs and regressions

### LINKED ISSUE #1407: Off-by-one line numbers in errors
**Description**
Line numbers for both compiler errors and runtime exceptions are 1 less than the actual line number that the error occurs in. 

**Reproduction**
1. Run cell that will produce an error (e.g. reassign a val) 
2. Expected behavior: error message contains line and column number of problematic line. Actual behavior: error message lists line number - 1. 

**Environment**
- Polynote Version: 
   - 0.5.2

**Screenshots**
Screenshot 2023-08-30 at 1 42 02 PM

### PR DESCRIPTION
**Pull request by jeremyrsmith**
- Jump-to-definition broke on merge, largely because of Monaco version change. This PR significantly reworks it. It doesn't seem to work in Python (jedi returns nulls); will try to solve that in a future release.
- Fixed regression where closed tabs reappear on reload
- Fixed off-by-one error (Fixes #1407 - but not properly)
- Compile error line-number links now jump to that spot in the cell

### CODE REVIEW

File: polynote-frontend/polynote/ui/component/notebook/cell.ts [hunk 1]
```diff
@@ -786,6 +786,15 @@ abstract class MonacoCell extends Cell {
             // overflowWidgetsDomNode: this.overflowDomNode
         });
 
+        // None of the official ways to do this seem to work
+
```
Comment (jeremyrsmith) [inline polynote-frontend/polynote/ui/component/notebook/cell.ts:790]: This is really unfortunate, but it seems to be the "correct-est" way to get sane behavior out of jump-to-definition. Monaco still calls to the server as soon as you hover a symbol, but it won't try to open a tab until you click (before, any time monaco initiated a jump-to-definition, it would result in polynote going forward with it. The monaco update included a change where monaco initiates a jump-to-definition on cmd-hover, for a "peek" feature that we're not using but can't be turned off)

File: polynote-kernel/src/main/scala/polynote/kernel/Kernel.scala [hunk 2]
```diff
@@ -32,7 +32,12 @@ trait Kernel {
   /**
     * Provide a location for the definition of whatever is at the given position in the given cell
     */
-  def goToDefinition(fileOrCell: Either[String, CellID], pos: Int): TaskC[(List[DefinitionLocation], Option[String])]
+  def goToDefinition(fileOrCell: Either[String, CellID], pos: Int): TaskC[List[DefinitionLocation]]
+
+  /**
+    * Retrieve the source of the given dependency identifier from the given language
+    */
+  def dependencySource(language: String, dependency: String): RIO[BaseEnv with GlobalEnv, String]
```
Comment (jeremyrsmith) [inline polynote-kernel/src/main/scala/polynote/kernel/Kernel.scala:40]: Split this back up, so we separately get the definition locations, and then can ask for the source code in a different request. The dependency sources are now handled differently – they're requested in a separate HTTP request instead of over the websocket.

File: polynote-frontend/polynote/ui/component/notebook/cell.ts [hunk 3]
```diff
@@ -1991,8 +2007,17 @@ class CodeCellOutput extends Disposable {
                             ]);
 
                             if (report.position) {
-                                const lineNumber = linePosAt(this.cellState.state.content, report.position.point)
-                                el.appendChild(span(['error-link'], [`(Line ${lineNumber})`]))
+                                // TODO: this is really discombobulated. Why does this have to call this function
+                                //        when the cell uses the editor model to translate the position? It's not
+                                //        "cleaner". I guess the cell should have a mapped view of the compile errors
+                                //        and pass that to the output component instead?
+                                const linePos = linePosAt(this.cellState.state.content, report.position.point)
```
Comment (jonathanindig) [inline polynote-frontend/polynote/ui/component/notebook/cell.ts:2014]: Since this is the only usage of `linePosAt` maybe we should just have it return a 1-based line number?

File: polynote-frontend/polynote/ui/component/notebook/cell.ts (hunk 1 above)
Comment (jonathanindig) [reply polynote-frontend/polynote/ui/component/notebook/cell.ts:790]: Trying to understand how this works. I guess it's monkey-patching [this function](https://github.com/microsoft/vscode/blob/dd112ec0243c4b42bb3106e64df1688e242a6559/src/vs/editor/browser/services/abstractCodeEditorService.ts#L275) ?

So basically we have Monaco ignore all "codeEditorOpenHandlers", whatever that is? 

> Monaco still calls to the server as soon as you hover a symbol

Are we just ignoring those calls then? Is there any way we can just swallow mouse-hover-while-holding-down-cmd events before they get to Monaco or is that too hacky?

File: polynote-frontend/polynote/ui/component/notebook/common.ts [hunk 4]
```diff
@@ -18,35 +19,69 @@ export function goToDefinition(
...
+    const filename = params.get("dependency");
+    const filePieces = filename?.split('.')
+    const fileLanguage = filePieces?.[filePieces.length - 1] || lang;
+
+    if (uriString in ServerStateHandler.state.dependencySources) {
+        return ServerStateHandler.get.updateAsync(state => {
+            const fileIsOpen = arrExists(state.openFiles, of => of.path === uriString);
+            return {
+                dependencySources: updateProperty(uriString, {position: Range.getStartPosition(location.range)}),
+                openFiles: fileIsOpen ? NoUpdate : append({type: "dependency_source", path: uriString})
```
Comment (jonathanindig) [inline polynote-frontend/polynote/ui/component/notebook/common.ts:54]: Hm, I wonder whether it would be possible to do the update to `openFiles` based on the update to `dependencySources`. Just to prevent needing to remember to update both?

File: polynote-kernel/src/main/scala/polynote/kernel/Kernel.scala (hunk 2 above)
Comment (jonathanindig) [reply polynote-kernel/src/main/scala/polynote/kernel/Kernel.scala:40]: What motivated the change?

File: polynote-frontend/polynote/ui/component/notebook/common.ts [hunk 5]
```diff
@@ -18,35 +19,69 @@ export function goToDefinition(
...
+    if (location.uri.fragment) {
+        const cellId = cellIdFromHash(location.uri.fragment);
+        notebookState.selectCellAt(cellId, Range.getStartPosition(location.range));
+        return Promise.resolve();
+    }
+
+    const params = new URLSearchParams(location.uri.query);
+    const filename = params.get("dependency");
+    const filePieces = filename?.split('.')
+    const fileLanguage = filePieces?.[filePieces.length - 1] || lang;
```
Comment (jonathanindig) [inline polynote-frontend/polynote/ui/component/notebook/common.ts:47]: I guess this is extracting the extension of the dependency file. Is that reliable? (i.e., extension is "py" but the language is "python"). When would it be different from the `lang` argument to `openDefinition`?

Also, don't we already have a `lang=$lang` query parameter in the URL?

File: polynote-kernel/src/main/scala/polynote/kernel/Kernel.scala (hunk 2 above)
Comment (jeremyrsmith) [reply polynote-kernel/src/main/scala/polynote/kernel/Kernel.scala:40]: Mainly, it's how Monaco wants it to be

File: polynote-frontend/polynote/ui/component/notebook/common.ts (hunk 5 above)
Comment (jeremyrsmith) [reply polynote-frontend/polynote/ui/component/notebook/common.ts:47]: That lang is the lang of the interpreter. But for example, you can jump to a Java source from a Scala cell.

Good point about python. It doesn't seem to work now anyway, so we'll have to work on it.

File: polynote-kernel/src/main/scala/polynote/kernel/interpreter/scal/SemanticDbScan.scala [hunk 6]
```diff
@@ -70,20 +116,47 @@ class SemanticDbScan (compiler: ScalaCompiler) {
...
+          }
+      }.zipLeft(ZIO {
+        semanticdbGlobal.settings.stopAfter.value = List("typer")
+        run = new semanticdbGlobal.Run()
+      })
+  }
 
 }
 
+object SemanticDbScan {
```
Comment (jonathanindig) [inline polynote-kernel/src/main/scala/polynote/kernel/interpreter/scal/SemanticDbScan.scala:159]: unnecessary object?

Comment (jeremyrsmith) [reply polynote-kernel/src/main/scala/polynote/kernel/interpreter/scal/SemanticDbScan.scala:159]: Yeah, I need to put an effectful constructor in here.

File: polynote-kernel/src/main/scala/polynote/kernel/interpreter/python/PythonInterpreter.scala [hunk 7]
```diff
@@ -255,29 +255,29 @@ class PythonInterpreter private[python] (
...
     locations   <- definitionLocations(script, line, col)
-    source      <- definitionSource(locations)
-  } yield (locations, source)
+  } yield locations
 
-  override def getDependencyContent(uri: String): RIO[Blocking, String] = ZIO {
-    val parsed = new URI(uri)
-    Files.readAllLines(Paths.get(parsed.getPath)).asScala.mkString("\n")
+  override def getDependencyContent(uri: String): RIO[Blocking, String] = ZIO(new URI(uri)).flatMap {
+    // TODO: some better checking that it's OK to read this path. Maybe goToDefinition should keep track of
```
Comment (jonathanindig) [inline polynote-kernel/src/main/scala/polynote/kernel/interpreter/python/PythonInterpreter.scala:277]: +1 to this idea. As it is now, you can hit `/dependency/path/to/anything` and see any file on the machine, right? Could you even do ``/dependency/../../../path/to/anything`?

File: polynote-frontend/polynote/ui/component/notebook/cell.ts (hunk 1 above)
Comment (jeremyrsmith) [reply polynote-frontend/polynote/ui/component/notebook/cell.ts:790]: Yeah, it's monkey patching. Supposedly there's some way to override this stuff from the editor constructor, but the examples are from years ago and don't work anymore.

> or is that too hacky?

... I mean. Look at this code. But I think this is a little closer to working with Monaco than against. And theoretically we could support the peek feature now (because Monaco gets a real http url that it can fetch the definition source code from)

File: polynote-kernel/src/main/scala/polynote/kernel/interpreter/python/PythonInterpreter.scala (hunk 7 above)
Comment (jeremyrsmith) [reply polynote-kernel/src/main/scala/polynote/kernel/interpreter/python/PythonInterpreter.scala:277]: Well, it has to be a .py file. But yes. The urls would be absolute, too — no need for the ..s

Comment (jeremyrsmith) [reply polynote-kernel/src/main/scala/polynote/kernel/interpreter/python/PythonInterpreter.scala:277]: We can disable this for now, since locating the definitions doesn't seem to work anymore anyway.

File: polynote-frontend/polynote/ui/component/notebook/cell.ts (hunk 1 above)
Comment (jonathanindig) [reply polynote-frontend/polynote/ui/component/notebook/cell.ts:790]: > Look at this code. 
😅 

> Monaco gets a real http url that it can fetch the definition source code from

Ah, I see. Monaco needs to be able to GET the URI independently in order to implement the "peek" feature? Too bad it can't just ask for data like it does for completions, etc. Have you considered monkey-patching that part or do you feel like it'd be too big a change to make (working against Monaco too much).

File: polynote-kernel/src/main/scala/polynote/kernel/interpreter/python/PythonInterpreter.scala (hunk 7 above)
Comment (jeremyrsmith) [reply polynote-kernel/src/main/scala/polynote/kernel/interpreter/python/PythonInterpreter.scala:277]: I suppose it would. Anyway, I'll just turn this method into a stub before merging (since the relevant jedi functionality seems to have stopped working anyhow). When we are able to properly support python jump-to-definition, we can implement the idea in the TODO.
