### PR TITLE
Fix run to cursor

### LINKED ISSUE #152: Run to cell broken?
@faisalzs noticed that run to cell might have been broken by some recent changes.

### PR DESCRIPTION
**Pull request by jeremyrsmith**
Fixes #152

### CODE REVIEW

File: polynote-frontend/polynote/ui.js [hunk 1]
```diff
@@ -929,7 +929,8 @@ export class NotebookUI extends UIEventTarget {
         });
 
         this.cellUI.addEventListener('RunToCursor', () => {
-            const activeCellIdx = Cell.currentFocus.id;
+            const allCellIds = this.cellUI.getCodeCellIds();
+            const activeCellIdx = allCellIds.indexOf(Cell.currentFocus.id);
```
Comment (jeremyrsmith) [inline polynote-frontend/polynote/ui.js]: Note: cell ID is not necessarily the cell index. It's kind of confusing now that we are using numeric IDs.

Comment (indig) [reply polynote-frontend/polynote/ui.js]: Ah, good catch, thanks! 😅
