### PR TITLE
Fix typing of runtime elements; static types for python results

### LINKED ISSUE #17: Somehow Python result can stop imports from working
Bit baffled by this one. Running a Python cell (not all Python cells though) before an import can cause a weird error message on the import. 

See the following ipynb file for an example:

```
{
  "metadata" : {
    
  },
  "nbformat" : 4,
  "nbformat_minor" : 0,
  "cells" : [
    {
      "cell_type" : "markdown",
      "execution_count" : 0,
      "language" : "text",
      "source" : [
        "# test imports 2\n",
        "\n",
        "This is a text cell. Start editing!"
      ],
      "outputs" : [
      ]
    },
    {
      "cell_type" : "code",
      "execution_count" : 3,
      "language" : "scala",
      "source" : [
        "import java.net.URL"
      ],
      "outputs" : [
      ]
    },
    {
      "cell_type" : "code",
      "execution_count" : 1,
      "language" : "python",
      "source" : [
        "[1, 2, 3, 4]"
      ],
      "outputs" : [
        {
          "execution_count" : 1,
          "data" : {
            "text/plain" : [
            ]
          },
          "output_type" : "execute_result"
        },
        {
          "execution_count" : 1,
          "data" : {
            "text/plain" : [
              "[1, 2, 3, 4]"
            ]
          },
          "output_type" : "execute_result"
        }
      ]
    },
    {
      "cell_type" : "code",
      "execution_count" : 2,
      "language" : "scala",
      "source" : [
        "import java.net.URL"
      ],
      "outputs" : [
        {
          "execution_count" : 2,
          "data" : {
            "application/json" : [
              {
                "pos" : {
                  "sourceId" : "Cell2",
                  "start" : 0,
                  "end" : 0,
                  "point" : 0
                },
                "msg" : "kinds of the type arguments (collection.immutable.::) do not conform to the expected kinds of the type parameters (type T0).\ncollection.immutable.::'s type parameters do not match type T0's expected parameters:\nclass :: has one type parameter, but type T0 has none",
                "severity" : 2
              }
            ],
            "text/plain" : [
              "Error: kinds of the type arguments (collection.immutable.::) do not conform to the expected kinds of the type parameters (type T0).\ncollection.immutable.::'s type parameters do not match type T0's expected parameters:\nclass :: has one type parameter, but type T0 has none (0)"
            ]
          },
          "metadata" : {
            "rel" : "compiler_errors"
          },
          "output_type" : "execute_result"
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by jeremyrsmith**
Fixes #17 in two ways:

- Better handling of runtime types – previously a runtime type that had type parameters would result in a type constructor being assigned as the static type. We can't recover the actual type parameters due to erasure, so instead we now fill in `Any` for them.
- Python interpreter now assigns static types to its results, to the best of its ability.

### CODE REVIEW

File: polynote-kernel/src/main/scala/polynote/kernel/lang/python/PythonInterpreter.scala [hunk 1]
```diff
@@ -143,7 +143,14 @@ class PythonInterpreter(val symbolTable: RuntimeSymbolTable) extends LanguageKer
     out: Enqueue[IO, Result],
     statusUpdates: Publish[IO, KernelStatusUpdate]
   ): IO[Unit] = if (code.trim().isEmpty) IO.unit else {
+    import symbolTable.global
+
     val stdout = new PythonDisplayHook(out)
+
+    global.demandNewCompilerRun()
+    val run = new global.Run()
+    global.newCompilationUnit("", cell)
```
Comment (indig) [inline polynote-kernel/src/main/scala/polynote/kernel/lang/python/PythonInterpreter.scala]: What do these lines do?

Comment (indig) [reply polynote-kernel/src/main/scala/polynote/kernel/lang/python/PythonInterpreter.scala]: The reason I asked: https://github.com/polynote/polynote/issues/51 😛
